### ISSUE TITLE
Atualização para versão 2015

### ISSUE THREAD

**Issue by mhalano** [monicapy/tugunisinos#4]
Existe uma versão 2015 da norma da biblioteca que, acredito, seria interessante publicar as atualizações

**Comment by wandersonwhcr** [comment]
Estou fazendo ;)

**Comment by wandersonwhcr** [comment]
@mhalano conseguiu utilizar? está precisando de alguma ajuda?

**Comment by mhalano** [comment]
Oi!

Não estou usando o LaTeX por enquanto.  Só acho interessante manter
atualizado para ser uma alternativa viável.

:)

On Mon, Jun 13, 2016, 16:45 Wanderson Camargo <notifications@github.com>
wrote:

> @mhalano <https://github.com/mhalano> conseguiu utilizar? está precisando
> de alguma ajuda?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/monicapy/tugunisinos/issues/4#issuecomment-225687200>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFvvRw-_ijbokSP58h6QnfaDbHz7OKb6ks5qLbNtgaJpZM4IuiSG>
> .
>
-- 

Sent from my Android
